"use strict";

/*-----------------------------------------------------------------
* jmp_score.js
* Helper module with defines and functions supporting 
* the JavaScript language scoring code generated by JMP
*
* Now browser-compatible (no require/module.exports)
*-----------------------------------------------------------------*/

var jmp = (function () {
    var squish = function(x) {
        return 1.0 / (1.0 + Math.exp(-x));
    };

    var squash = function(x) {
        return 1.0 / (1.0 + Math.exp(x));
    };

    var is_missing = function (x) {
        return (typeof x == 'number' && (isNaN(x) || !isFinite(x))) || x === undefined;
    };

    /*-----------------------------------------------------------------
    * Return the index of the max value found in an array
    * or -1 if all are missing
    *-----------------------------------------------------------------*/
    var max_array = function(n, lst) {
        var maxval = -Infinity;
        var maxidx = -1;
        var count_miss = 0;
        
        for (var i = 0; i < n; i++) {
            if (is_missing(lst[i])) {
                count_miss++;
            } else if (maxval < lst[i]) {
                maxval = lst[i];
                maxidx = i;
            }
        }
        return (count_miss == n) ? -1 : maxidx;
    };

    /*-----------------------------------------------------------------
    * Return the index of the min value found in an array
    * or -1 if all are missing
    *-----------------------------------------------------------------*/
    var min_array = function(n, lst) {
        var minval = Infinity;
        var minidx = -1;
        var count_miss = 0;
        
        for (var i = 0; i < n; i++) {
            if (is_missing(lst[i])) {
                count_miss++;
            } else if (minval > lst[i]) {
                minval = lst[i];
                minidx = i;
            }
        }
        return (count_miss == n) ? -1 : minidx;
    };

    /*-----------------------------------------------------------------
    * Returns true if the numbers are identical using straight comparison.
    * If necessary, replace with a suitable comparison using a value of EPSILON
    * appropriate for your domain.
    *-----------------------------------------------------------------*/
    var numeq = function(x, y) {
        return x == y;
    };

    // Expose the functions in a global "jmp" object
    return {
        squish: squish,
        squash: squash,
        is_missing: is_missing,
        max_array: max_array,
        min_array: min_array,
        numeq: numeq
    };
})();
