
console.log("model.js is loaded!");

"use strict";

/* ====================================================================
 Copyright (C) 2022 JMP Statistical Discovery LLC. All rights reserved.
 
 Notice: The following permissions are granted provided that the above
 copyright and this notice appear in the score code and any related
 documentation. Permission to copy, modify and distribute the score
 code generated using JMP (r) software is limited to customers of JMP
 Statistical Discovery LLC ("JMP") and successive third parties, all
 without any warranty, express or implied, or any other obligation by
 JMP. JMP and all other JMP Statistical Discovery LLC product and
 service names are registered trademarks or trademarks of JMP
 Statistical Discovery LLC in the USA and other countries. Except as
 contained in this notice, the name of JMP shall not be used in the
 advertising or promotion of products or services without prior
 written authorization from  Statistical Discovery LLC.
 ==================================================================== */

/* JavaScript code generated by JMP 17.0.0 */
var getModelMetadata = function() {
	return {"creator": "Neural", "modelName": "Model NTanH(3)NLinear(3)NGaussian(3)NBoost(1) - Save Formulas", "predicted": "Clinical Trial enrollment: (Yes=1, No =2)", "table": "david Advances Paper whole cohort with DFCI and added UPDATED kps insurance employ lobe External validation dataset-updated 2025 02 17 - Copy 1-2 (2).jmp", "version": "17.0.0", "timestamp": "2025-03-13T20:16:41Z"};
};

var getInputMetadata = function() {
    return {
   "$schema": "http://json-schema.org/draft-04/schema#",
   "id": "/",
   "type": "object",
   "properties": {
     "Age.at.Initial.Diagnosis": {
       "id": "Age.at.Initial.Diagnosis",
       "type": "number"
     },
     "Employed(Y=1, N=2, Retired=3) 2": {
       "id": "Employed(Y=1, N=2, Retired=3) 2",
       "type": "number"
     },
     "Ethnicity Hispanic/Latino (Yes=1, No=2) 2": {
       "id": "Ethnicity Hispanic/Latino (Yes=1, No=2) 2",
       "type": "number"
     },
     "KPS.post.op 3": {
       "id": "KPS.post.op 3",
       "type": "number"
     },
     "New Tumor Lobe (updated chart review) 2 2 2": {
       "id": "New Tumor Lobe (updated chart review) 2 2 2",
       "type": "number"
     },
     "Reordered insurance at diagnosis 2 2": {
       "id": "Reordered insurance at diagnosis 2 2",
       "type": "number"
     },
     "Seizure.preop 2": {
       "id": "Seizure.preop 2",
       "type": "number"
     },
     "Sex (M=1, F=2)": {
       "id": "Sex (M=1, F=2)",
       "type": "number"
     },
     "TMZ anytime 2 2": {
       "id": "TMZ anytime 2 2",
       "type": "number"
     },
     "Updated Race White, Black/African American, Hispanic/Latino, Asian/Pacific Islander, American Indian/Alaska Native 3 2": {
       "id": "Updated Race White, Black/African American, Hispanic/Latino, Asian/Pacific Islander, American Indian/Alaska Native 3 2",
       "type": "number"
     },
     "WHO Grade 2 2": {
       "id": "WHO Grade 2 2",
       "type": "number"
     }   },
   "additionalProperties": false,
  };
};

var getOutputMetadata = function() {
    return {
   "$schema": "http://json-schema.org/draft-04/schema#",
   "id": "/",
   "type": "object",
   "properties": {
     "ProbabilityEnroll": {
       "id": "ProbabilityEnroll",
       "type": "number"
     },
     "ProbabilityNotEnroll": {
       "id": "ProbabilityNotEnroll",
       "type": "number"
     },
     "MostLikelyClinicalTrial": {
       "id": "MostLikelyClinicalTrial",
       "type": "number"
     }   },
   "additionalProperties": false,
  };
};

var score = function(indata, outdata) {
   console.log("✅ model.js received input:", indata); 
 // Original name was: 'WHO Grade 2 2_asCode'
    var WHO_Grade_2_2_asCode;
    // Original name was: 'Updated Race (White, Black/African American, Hispanic/Latino, Asian/Pacific Islander, American Indian/Alaska Native 3 2_asCode'
    var Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode;
    // Original name was: 'TMZ anytime 2 2_asCode'
    var TMZ_anytime_2_2_asCode;
    // Original name was: 'Sex (M=1, F=2)_asCode'
    var Sex_M_1_F_2__asCode;
    // Original name was: 'Seizure.preop 2_asCode'
    var Seizure_preop_2_asCode;
    // Original name was: 'Reordered insurance at diagnosis 2 2_asCode'
    var Reordered_insurance_at_diagnosis_2_2_asCode;
    // Original name was: 'New Tumor Lobe (updated chart review) 2 2 2_asCode'
    var New_Tumor_Lobe_updated_chart_review_2_2_2_asCode;
    // Original name was: 'KPS.post.op 3_asCode'
    var KPS_post_op_3_asCode;
    // Original name was: 'Ethnicity Hispanic/Latino (Yes=1, No=2) 2_asCode'
    var Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode;
    // Original name was: 'Employed(Y=1, N=2, Retired=3) 2_asCode'
    var Employed_Y_1_N_2_Retired_3_2_asCode;
    var H1_1_1;
    var H1_2_1;
    var H1_3_1;
    var H1_4_1;
    var H1_5_1;
    var H1_6_1;
    var H1_7_1;
    var H1_8_1;
    var H1_9_1;
    var _temp_0 = undefined;
    var _temp_1 = undefined;
    var _temp_2 = undefined;
    var _temp_3 = undefined;
    var _temp_4 = undefined;
    var _temp_5 = undefined;
    var _temp_6 = undefined;
    var _temp_7 = undefined;
    var _temp_8 = undefined;
    var _temp_9 = undefined;
    var _temp_10;
    var _temp_11 = [];
	console.log("✅ model.js score() function is executing");
console.log("🚀 Checking indata:", JSON.stringify(indata, null, 2));
	
    if (indata["WHO Grade 2 2"] === 0)  {
        _temp_0 = 0;
    }
    else if (indata["WHO Grade 2 2"] === 1)  {
        _temp_0 = 1;
    }
else {
    console.warn("⚠️ WHO Grade 2 2 not recognized:", indata["WHO Grade 2 2"]);
}
	console.log("Printng temp 0 value right before reassigning to asCode for WHO grade:", _temp_0);
    WHO_Grade_2_2_asCode = _temp_0;
	console.log("Printing recoded asCode versions of variables once passed to model.js. WHO Grade:", WHO_Grade_2_2_asCode);

    if (indata["Updated Race White, Black/African American, Hispanic/Latino, Asian/Pacific Islander, American Indian/Alaska Native 3 2"] === 0)  {
        _temp_0 = 0;
    }
    else if (indata["Updated Race White, Black/African American, Hispanic/Latino, Asian/Pacific Islander, American Indian/Alaska Native 3 2"] === 1)  {
        _temp_0 = 1;
    }
    else if (indata["Updated Race White, Black/African American, Hispanic/Latino, Asian/Pacific Islander, American Indian/Alaska Native 3 2"] === 2)  {
        _temp_0 = 2;
    }
    else if (indata["Updated Race White, Black/African American, Hispanic/Latino, Asian/Pacific Islander, American Indian/Alaska Native 3 2"] === 3)  {
        _temp_0 = 3;
    }
    else if (indata["Updated Race White, Black/African American, Hispanic/Latino, Asian/Pacific Islander, American Indian/Alaska Native 3 2"] === 4)  {
        _temp_0 = 4;
    }
    else if (indata["Updated Race White, Black/African American, Hispanic/Latino, Asian/Pacific Islander, American Indian/Alaska Native 3 2"] === 5)  {
        _temp_0 = 5;
    }
    else if (indata["Updated Race White, Black/African American, Hispanic/Latino, Asian/Pacific Islander, American Indian/Alaska Native 3 2"] === 6)  {
        _temp_0 = 6;
    }
	console.log("Printng temp 0 value right before reassigning to asCode for race:", _temp_0);
    Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode = _temp_0;
	console.log("Printing recoded asCode versions of variables once passed to model.js. Race:", Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode);
    if (indata["TMZ anytime 2 2"] === 0)  {
        _temp_0 = 0;
    }
    else if (indata["TMZ anytime 2 2"] === 1)  {
        _temp_0 = 1;
    }
    else if (indata["TMZ anytime 2 2"] === 2)  {
        _temp_0 = 2;
    }
	console.log("Printng temp 0 value right before reassigning to asCode for Chemo:", _temp_0);
    TMZ_anytime_2_2_asCode = _temp_0;
	console.log("Printing recoded asCode versions of variables once passed to model.js. TMZ Chemo:", TMZ_anytime_2_2_asCode);

	if (indata["Sex (M=1, F=2)"] === 1)  {
        _temp_0 = 0;
    }
    else if (indata["Sex (M=1, F=2)"] === 2)  {
        _temp_0 = 1;
    }
	console.log("Printng temp 0 value right before reassigning to asCode for Sex:", _temp_0);
    Sex_M_1_F_2__asCode = _temp_0;
	console.log("Printing recoded asCode versions of variables once passed to model.js. Sex:", Sex_M_1_F_2__asCode);

    if (indata["Seizure.preop 2"] === 0)  {
        _temp_0 = 0;
    }
    else if (indata["Seizure.preop 2"] === 1)  {
        _temp_0 = 1;
    }
    else if (indata["Seizure.preop 2"] === 2)  {
        _temp_0 = 2;
    }
	console.log("Printng temp 0 value right before reassigning to asCode for Seizure:", _temp_0);
    Seizure_preop_2_asCode = _temp_0;
	console.log("Printing recoded asCode versions of variables once passed to model.js. Seizure:", Seizure_preop_2_asCode);

    if (indata["Reordered insurance at diagnosis 2 2"] === 0)  {
        _temp_0 = 0;
    }
    else if (indata["Reordered insurance at diagnosis 2 2"] === 1)  {
        _temp_0 = 1;
    }
    else if (indata["Reordered insurance at diagnosis 2 2"] === 2)  {
        _temp_0 = 2;
    }
    else if (indata["Reordered insurance at diagnosis 2 2"] === 3)  {
        _temp_0 = 3;
    }
    else if (indata["Reordered insurance at diagnosis 2 2"] === 4)  {
        _temp_0 = 4;
    }
	console.log("Printng temp 0 value right before reassigning to asCode for insurance:", _temp_0);
    Reordered_insurance_at_diagnosis_2_2_asCode = _temp_0;
	console.log("Printing recoded asCode versions of variables once passed to model.js. Insurance:", Reordered_insurance_at_diagnosis_2_2_asCode);

    if (indata["New Tumor Lobe (updated chart review) 2 2 2"] === 0)  {
        _temp_0 = 0;
    }
    else if (indata["New Tumor Lobe (updated chart review) 2 2 2"] === 1)  {
        _temp_0 = 1;
    }
    else if (indata["New Tumor Lobe (updated chart review) 2 2 2"] === 2)  {
        _temp_0 = 2;
    }
    else if (indata["New Tumor Lobe (updated chart review) 2 2 2"] === 3)  {
        _temp_0 = 3;
    }
    else if (indata["New Tumor Lobe (updated chart review) 2 2 2"] === 4)  {
        _temp_0 = 4;
    }
    else if (indata["New Tumor Lobe (updated chart review) 2 2 2"] === 5)  {
        _temp_0 = 5;
    }
    else if (indata["New Tumor Lobe (updated chart review) 2 2 2"] === 6)  {
        _temp_0 = 6;
    }
    else if (indata["New Tumor Lobe (updated chart review) 2 2 2"] === 7)  {
        _temp_0 = 7;
    }
	console.log("Printng temp 0 value right before reassigning to asCode for tumor lobe:", _temp_0);
    New_Tumor_Lobe_updated_chart_review_2_2_2_asCode = _temp_0;
	console.log("Printing recoded asCode versions of variables once passed to model.js. Tumor lobe:", New_Tumor_Lobe_updated_chart_review_2_2_2_asCode);

    if (indata["KPS.post.op 3"] === 0)  {
        _temp_0 = 0;
    }
    else if (indata["KPS.post.op 3"] === 1)  {
        _temp_0 = 1;
    }
    else if (indata["KPS.post.op 3"] === 2)  {
        _temp_0 = 2;
    }
    else if (indata["KPS.post.op 3"] === 3)  {
        _temp_0 = 3;
    }
    else if (indata["KPS.post.op 3"] === 4)  {
        _temp_0 = 4;
    }
	console.log("Printng temp 0 value right before reassigning to asCode for KPS:", _temp_0);
    KPS_post_op_3_asCode = _temp_0;
console.log("Printing recoded asCode versions of variables once passed to model.js. KPS:", KPS_post_op_3_asCode);
    if (indata["Ethnicity Hispanic/Latino (Yes=1, No=2) 2"] === 0)  {
        _temp_0 = 0;
    }
    else if (indata["Ethnicity Hispanic/Latino (Yes=1, No=2) 2"] === 1)  {
        _temp_0 = 1;
    }
    else if (indata["Ethnicity Hispanic/Latino (Yes=1, No=2) 2"] === 2)  {
        _temp_0 = 2;
    }
	console.log("Printng temp 0 value right before reassigning to asCode for Ethnicity:", _temp_0);
    Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode = _temp_0;
console.log("Printing recoded asCode versions of variables once passed to model.js. Ethnicity:", Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode);
    if (indata["Employed(Y=1, N=2, Retired=3) 2"] === 0)  {
        _temp_0 = 0;
    }
    else if (indata["Employed(Y=1, N=2, Retired=3) 2"] === 1)  {
        _temp_0 = 1;
    }
    else if (indata["Employed(Y=1, N=2, Retired=3) 2"] === 2)  {
        _temp_0 = 2;
    }
    else if (indata["Employed(Y=1, N=2, Retired=3) 2"] === 3)  {
        _temp_0 = 3;
    }
	console.log("Printng temp 0 value right before reassigning to asCode for Employment:", _temp_0);
	Employed_Y_1_N_2_Retired_3_2_asCode = _temp_0;
	console.log("Printing recoded asCode versions of variables once passed to model.js. Employment:", Employed_Y_1_N_2_Retired_3_2_asCode);
	
	if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 0))  {
        _temp_0 = 0.0126647781310412;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 1))  {
        _temp_0 = 0.309197965915521;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 2))  {
        _temp_0 = 0.669498828034819;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 3))  {
        _temp_0 = -0.991361572081381;
    }
    if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 0))  {
        _temp_1 = -2.1192210469104;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 1))  {
        _temp_1 = 1.03185006171115;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 2))  {
        _temp_1 = 1.08737098519924;
    }
    if (jmp.numeq(KPS_post_op_3_asCode, 0))  {
        _temp_2 = -0.128876200026932;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 1))  {
        _temp_2 = -0.418557414449981;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 2))  {
        _temp_2 = -0.607157784508581;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 3))  {
        _temp_2 = -0.254941401833931;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 4))  {
        _temp_2 = 1.40953280081943;
    }
    if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 0))  {
        _temp_3 = -0.522776551234623;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 1))  {
        _temp_3 = 0.518897799531689;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 2))  {
        _temp_3 = 0.590201639772647;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 3))  {
        _temp_3 = -1.54512163100558;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 4))  {
        _temp_3 = -0.161403267527723;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 5))  {
        _temp_3 = -0.524604515773605;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 6))  {
        _temp_3 = 0.460018344195113;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 7))  {
        _temp_3 = 1.18478818204209;
    }
    if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 0))  {
        _temp_4 = 0.0414587108927191;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 1))  {
        _temp_4 = -0.795725093056595;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 2))  {
        _temp_4 = 0.270277193511541;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 3))  {
        _temp_4 = 1.29427092128196;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 4))  {
        _temp_4 = -0.810281732629625;
    }
    if (jmp.numeq(Seizure_preop_2_asCode, 0))  {
        _temp_5 = -0.085890996359661;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 1))  {
        _temp_5 = 0.363711685084149;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 2))  {
        _temp_5 = -0.277820688724488;
    }
    if (jmp.numeq(Sex_M_1_F_2__asCode, 0))  {
        _temp_6 = 0.0590326968729796;
    }
    else if (jmp.numeq(Sex_M_1_F_2__asCode, 1))  {
        _temp_6 = -0.0590326968729796;
    }
    if (jmp.numeq(TMZ_anytime_2_2_asCode, 0))  {
        _temp_7 = 0.403190026413261;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 1))  {
        _temp_7 = 0.717882687338789;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 2))  {
        _temp_7 = -1.12107271375205;
    }
    if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 0))  {
        _temp_8 = 0.041526556295255;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 1))  {
        _temp_8 = 0.464122110933867;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 2))  {
        _temp_8 = -0.292052566652274;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 3))  {
        _temp_8 = 0.136804358317674;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 4))  {
        _temp_8 = -0.498351967812851;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 5))  {
        _temp_8 = 0.224023851054048;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 6))  {
        _temp_8 = -0.0760723421357183;
    }
    if (jmp.numeq(WHO_Grade_2_2_asCode, 0))  {
        _temp_9 = 0.1992599287063;
    }
    else if (jmp.numeq(WHO_Grade_2_2_asCode, 1))  {
        _temp_9 = -0.1992599287063;
    }
    H1_1_1 = Math.tanh((-0.189498065814732 + -0.136904716750564 * Math.log(((-11.6322367884617 + indata["Age.at.Initial.Diagnosis"]) / (89.6435132764535 + -1 * indata["Age.at.Initial.Diagnosis"]))) + 0.5 * _temp_0 + 0.5 * _temp_1 + 0.5 * _temp_2 + 0.5 * _temp_3 + 0.5 * _temp_4 + 0.5 * _temp_5 + 0.5 * _temp_6 + 0.5 * _temp_7 + 0.5 * _temp_8 + 0.5 * _temp_9));
console.log("Printing first H1_1_1 value to check if mathematical formula is actually working and that the formula is calculating", H1_1_1);
	
    if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 0))  {
        _temp_0 = 0.0237751112385;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 1))  {
        _temp_0 = -0.119589881113633;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 2))  {
        _temp_0 = -0.183179258405702;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 3))  {
        _temp_0 = 0.278994028280835;
    }
    if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 0))  {
        _temp_1 = -0.13103201608362;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 1))  {
        _temp_1 = -0.359562198566828;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 2))  {
        _temp_1 = 0.490594214650448;
    }
    if (jmp.numeq(KPS_post_op_3_asCode, 0))  {
        _temp_2 = 0.190000047885672;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 1))  {
        _temp_2 = -0.0484618028677408;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 2))  {
        _temp_2 = 0.219577572600914;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 3))  {
        _temp_2 = 0.00718714258881147;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 4))  {
        _temp_2 = -0.368302960207657;
    }
    if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 0))  {
        _temp_3 = -0.164054667221823;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 1))  {
        _temp_3 = 0.182293098070349;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 2))  {
        _temp_3 = 0.135335128633436;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 3))  {
        _temp_3 = -0.234827889355523;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 4))  {
        _temp_3 = -0.0994536362977358;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 5))  {
        _temp_3 = -0.102905094750813;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 6))  {
        _temp_3 = -0.00472370540538925;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 7))  {
        _temp_3 = 0.288336766327499;
    }
    if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 0))  {
        _temp_4 = 0.0806764382978211;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 1))  {
        _temp_4 = 0.0334894985200533;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 2))  {
        _temp_4 = -0.21106594927284;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 3))  {
        _temp_4 = -0.10768295371216;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 4))  {
        _temp_4 = 0.204582966167125;
    }
    if (jmp.numeq(Seizure_preop_2_asCode, 0))  {
        _temp_5 = 0.0818806730589064;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 1))  {
        _temp_5 = -0.00975352005844342;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 2))  {
        _temp_5 = -0.072127153000463;
    }
    if (jmp.numeq(Sex_M_1_F_2__asCode, 0))  {
        _temp_6 = 0.114447236708397;
    }
    else if (jmp.numeq(Sex_M_1_F_2__asCode, 1))  {
        _temp_6 = -0.114447236708397;
    }
    if (jmp.numeq(TMZ_anytime_2_2_asCode, 0))  {
        _temp_7 = -0.187226401615626;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 1))  {
        _temp_7 = -0.39936619806525;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 2))  {
        _temp_7 = 0.586592599680876;
    }
    if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 0))  {
        _temp_8 = -0.0586176410940449;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 1))  {
        _temp_8 = -0.0752113924942198;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 2))  {
        _temp_8 = -0.0460104385490381;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 3))  {
        _temp_8 = 0.0357853850388568;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 4))  {
        _temp_8 = -0.0397828965391713;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 5))  {
        _temp_8 = 0.0797642102356416;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 6))  {
        _temp_8 = 0.104072773401976;
    }
    if (jmp.numeq(WHO_Grade_2_2_asCode, 0))  {
        _temp_9 = 0.0559314007859859;
    }
    else if (jmp.numeq(WHO_Grade_2_2_asCode, 1))  {
        _temp_9 = -0.0559314007859859;
    }
    H1_2_1 = Math.tanh((-0.0762627977282243 + 0.0205871086829871 * Math.log(((-11.6322367884617 + indata["Age.at.Initial.Diagnosis"]) / (89.6435132764535 + -1 * indata["Age.at.Initial.Diagnosis"]))) + 0.5 * _temp_0 + 0.5 * _temp_1 + 0.5 * _temp_2 + 0.5 * _temp_3 + 0.5 * _temp_4 + 0.5 * _temp_5 + 0.5 * _temp_6 + 0.5 * _temp_7 + 0.5 * _temp_8 + 0.5 * _temp_9));

    if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 0))  {
        _temp_0 = -0.274391997392113;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 1))  {
        _temp_0 = -0.362759186993244;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 2))  {
        _temp_0 = -1.01732157905126;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 3))  {
        _temp_0 = 1.65447276343662;
    }
    if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 0))  {
        _temp_1 = 0.986879199945021;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 1))  {
        _temp_1 = -0.807530978339541;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 2))  {
        _temp_1 = -0.17934822160548;
    }
    if (jmp.numeq(KPS_post_op_3_asCode, 0))  {
        _temp_2 = 0.549090180917004;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 1))  {
        _temp_2 = -0.8923219265539;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 2))  {
        _temp_2 = -0.223886256489718;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 3))  {
        _temp_2 = -0.666228635193298;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 4))  {
        _temp_2 = 1.23334663731991;
    }
    if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 0))  {
        _temp_3 = 0.872022634274192;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 1))  {
        _temp_3 = -0.214358708566237;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 2))  {
        _temp_3 = -0.502685692407909;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 3))  {
        _temp_3 = 0.115797173174908;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 4))  {
        _temp_3 = -0.670341348808783;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 5))  {
        _temp_3 = -0.162209768512847;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 6))  {
        _temp_3 = -0.67985274048561;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 7))  {
        _temp_3 = 1.24162845133229;
    }
    if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 0))  {
        _temp_4 = 0.290835126079651;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 1))  {
        _temp_4 = 1.97019657369012;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 2))  {
        _temp_4 = 0.284952943812342;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 3))  {
        _temp_4 = -1.30073194886113;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 4))  {
        _temp_4 = -1.24525269472098;
    }
    if (jmp.numeq(Seizure_preop_2_asCode, 0))  {
        _temp_5 = 0.303831848795094;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 1))  {
        _temp_5 = 0.778504940108678;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 2))  {
        _temp_5 = -1.08233678890377;
    }
    if (jmp.numeq(Sex_M_1_F_2__asCode, 0))  {
        _temp_6 = -0.502300916089368;
    }
    else if (jmp.numeq(Sex_M_1_F_2__asCode, 1))  {
        _temp_6 = 0.502300916089368;
    }
    if (jmp.numeq(TMZ_anytime_2_2_asCode, 0))  {
        _temp_7 = 0.525874818193079;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 1))  {
        _temp_7 = 1.42348112177065;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 2))  {
        _temp_7 = -1.94935593996372;
    }
    if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 0))  {
        _temp_8 = -0.0713855519069724;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 1))  {
        _temp_8 = -0.252190609272114;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 2))  {
        _temp_8 = 0.439025944932501;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 3))  {
        _temp_8 = 0.162571019200886;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 4))  {
        _temp_8 = 0.943109708800135;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 5))  {
        _temp_8 = 0.575596153715475;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 6))  {
        _temp_8 = -1.79672666546991;
    }
    if (jmp.numeq(WHO_Grade_2_2_asCode, 0))  {
        _temp_9 = 0.0247782137560995;
    }
    else if (jmp.numeq(WHO_Grade_2_2_asCode, 1))  {
        _temp_9 = -0.0247782137560995;
    }
    H1_3_1 = Math.tanh((1.94639019322895 + 0.121575394134246 * Math.log(((-11.6322367884617 + indata["Age.at.Initial.Diagnosis"]) / (89.6435132764535 + -1 * indata["Age.at.Initial.Diagnosis"]))) + 0.5 * _temp_0 + 0.5 * _temp_1 + 0.5 * _temp_2 + 0.5 * _temp_3 + 0.5 * _temp_4 + 0.5 * _temp_5 + 0.5 * _temp_6 + 0.5 * _temp_7 + 0.5 * _temp_8 + 0.5 * _temp_9));

    if (jmp.numeq(Sex_M_1_F_2__asCode, 0))  {
        _temp_0 = -0.251897754580172;
    }
    else if (jmp.numeq(Sex_M_1_F_2__asCode, 1))  {
        _temp_0 = 0.251897754580172;
    }
    if (jmp.numeq(WHO_Grade_2_2_asCode, 0))  {
        _temp_1 = -0.152612528600202;
    }
    else if (jmp.numeq(WHO_Grade_2_2_asCode, 1))  {
        _temp_1 = 0.152612528600202;
    }
    if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 0))  {
        _temp_2 = -0.316794695839407;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 1))  {
        _temp_2 = 0.105745617158737;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 2))  {
        _temp_2 = 0.21104907868067;
    }
    if (jmp.numeq(Seizure_preop_2_asCode, 0))  {
        _temp_3 = 0.124700905356195;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 1))  {
        _temp_3 = 0.0506312800298801;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 2))  {
        _temp_3 = -0.175332185386075;
    }
    if (jmp.numeq(TMZ_anytime_2_2_asCode, 0))  {
        _temp_4 = -0.039871286032984;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 1))  {
        _temp_4 = 0.457534743494519;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 2))  {
        _temp_4 = -0.417663457461535;
    }
    if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 0))  {
        _temp_5 = 0.791493576300955;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 1))  {
        _temp_5 = -0.0244513811845486;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 2))  {
        _temp_5 = 0.267432980339702;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 3))  {
        _temp_5 = -1.03447517545611;
    }
    if (jmp.numeq(KPS_post_op_3_asCode, 0))  {
        _temp_6 = -0.536673143491842;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 1))  {
        _temp_6 = -0.158187441018559;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 2))  {
        _temp_6 = -0.09793851464732;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 3))  {
        _temp_6 = 0.274251252297486;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 4))  {
        _temp_6 = 0.518547846860235;
    }
    if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 0))  {
        _temp_7 = 0.276669378678415;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 1))  {
        _temp_7 = 0.429437142110762;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 2))  {
        _temp_7 = 0.00124670811096565;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 3))  {
        _temp_7 = 0.751693087864656;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 4))  {
        _temp_7 = -1.4590463167648;
    }
    if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 0))  {
        _temp_8 = 0.180067411094595;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 1))  {
        _temp_8 = 0.345059940986432;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 2))  {
        _temp_8 = 0.0615586138474304;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 3))  {
        _temp_8 = 0.0983543245902029;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 4))  {
        _temp_8 = 0.223322914290811;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 5))  {
        _temp_8 = 0.107344667526001;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 6))  {
        _temp_8 = -1.01570787233547;
    }
    if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 0))  {
        _temp_9 = 0.605762805550004;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 1))  {
        _temp_9 = 0.628440758570829;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 2))  {
        _temp_9 = 0.0770149347486429;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 3))  {
        _temp_9 = 0.70600080476557;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 4))  {
        _temp_9 = 0.277749921327331;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 5))  {
        _temp_9 = 0.204546339953179;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 6))  {
        _temp_9 = 0.41687352871205;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 7))  {
        _temp_9 = -2.91638909362761;
    }
    H1_4_1 = 0.37251596956247 + -0.523130741290518 * Math.log(((-11.6322367884617 + indata["Age.at.Initial.Diagnosis"]) / (89.6435132764535 + -1 * indata["Age.at.Initial.Diagnosis"]))) + _temp_0 + _temp_1 + _temp_2 + _temp_3 + _temp_4 + _temp_5 + _temp_6 + _temp_7 + _temp_8 + _temp_9;

    if (jmp.numeq(Sex_M_1_F_2__asCode, 0))  {
        _temp_0 = -0.203233328371018;
    }
    else if (jmp.numeq(Sex_M_1_F_2__asCode, 1))  {
        _temp_0 = 0.203233328371018;
    }
    if (jmp.numeq(WHO_Grade_2_2_asCode, 0))  {
        _temp_1 = -0.140530898846484;
    }
    else if (jmp.numeq(WHO_Grade_2_2_asCode, 1))  {
        _temp_1 = 0.140530898846484;
    }
    if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 0))  {
        _temp_2 = -0.486085778919053;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 1))  {
        _temp_2 = 0.199933270601369;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 2))  {
        _temp_2 = 0.286152508317683;
    }
    if (jmp.numeq(Seizure_preop_2_asCode, 0))  {
        _temp_3 = 0.288971612737348;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 1))  {
        _temp_3 = 0.289212085755626;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 2))  {
        _temp_3 = -0.578183698492974;
    }
    if (jmp.numeq(TMZ_anytime_2_2_asCode, 0))  {
        _temp_4 = -0.044120770842349;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 1))  {
        _temp_4 = 0.424638172030899;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 2))  {
        _temp_4 = -0.38051740118855;
    }
    if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 0))  {
        _temp_5 = 0.54758857961864;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 1))  {
        _temp_5 = -0.265238755564156;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 2))  {
        _temp_5 = 0.200633872663683;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 3))  {
        _temp_5 = -0.482983696718166;
    }
    if (jmp.numeq(KPS_post_op_3_asCode, 0))  {
        _temp_6 = -0.426967966505769;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 1))  {
        _temp_6 = -0.271214800334143;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 2))  {
        _temp_6 = -0.263626728181626;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 3))  {
        _temp_6 = 0.00831109536918744;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 4))  {
        _temp_6 = 0.953498399652351;
    }
    if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 0))  {
        _temp_7 = 0.19102792349902;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 1))  {
        _temp_7 = 0.479066849899183;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 2))  {
        _temp_7 = 0.136978947786066;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 3))  {
        _temp_7 = 0.641996503520288;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 4))  {
        _temp_7 = -1.44907022470456;
    }
    if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 0))  {
        _temp_8 = 0.105592489706255;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 1))  {
        _temp_8 = 0.157501427687825;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 2))  {
        _temp_8 = 0.0738151860938938;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 3))  {
        _temp_8 = 0.126571916417749;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 4))  {
        _temp_8 = 0.170136881255551;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 5))  {
        _temp_8 = 0.0547920789253211;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 6))  {
        _temp_8 = -0.688409980086596;
    }
    if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 0))  {
        _temp_9 = 0.381994272940461;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 1))  {
        _temp_9 = -0.0389387255970636;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 2))  {
        _temp_9 = 0.0220987091610199;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 3))  {
        _temp_9 = 0.507904685717226;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 4))  {
        _temp_9 = 0.23522830207717;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 5))  {
        _temp_9 = 0.1393423512937;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 6))  {
        _temp_9 = 0.180364543226271;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 7))  {
        _temp_9 = -1.42799413881878;
    }
    H1_5_1 = 0.419465453293952 + -0.32545039843675 * Math.log(((-11.6322367884617 + indata["Age.at.Initial.Diagnosis"]) / (89.6435132764535 + -1 * indata["Age.at.Initial.Diagnosis"]))) + _temp_0 + _temp_1 + _temp_2 + _temp_3 + _temp_4 + _temp_5 + _temp_6 + _temp_7 + _temp_8 + _temp_9;

    if (jmp.numeq(Sex_M_1_F_2__asCode, 0))  {
        _temp_0 = -0.133516833393326;
    }
    else if (jmp.numeq(Sex_M_1_F_2__asCode, 1))  {
        _temp_0 = 0.133516833393326;
    }
    if (jmp.numeq(WHO_Grade_2_2_asCode, 0))  {
        _temp_1 = -0.0336622677703579;
    }
    else if (jmp.numeq(WHO_Grade_2_2_asCode, 1))  {
        _temp_1 = 0.0336622677703579;
    }
    if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 0))  {
        _temp_2 = -0.246424911636902;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 1))  {
        _temp_2 = 0.161292260706049;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 2))  {
        _temp_2 = 0.0851326509308533;
    }
    if (jmp.numeq(Seizure_preop_2_asCode, 0))  {
        _temp_3 = 0.221376442406625;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 1))  {
        _temp_3 = 0.288347323103547;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 2))  {
        _temp_3 = -0.509723765510172;
    }
    if (jmp.numeq(TMZ_anytime_2_2_asCode, 0))  {
        _temp_4 = -0.0144714382423183;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 1))  {
        _temp_4 = 0.169378534433135;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 2))  {
        _temp_4 = -0.154907096190817;
    }
    if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 0))  {
        _temp_5 = 0.00674811963560333;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 1))  {
        _temp_5 = -0.180339246474417;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 2))  {
        _temp_5 = 0.0358110854240547;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 3))  {
        _temp_5 = 0.137780041414759;
    }
    if (jmp.numeq(KPS_post_op_3_asCode, 0))  {
        _temp_6 = -0.0231670913950572;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 1))  {
        _temp_6 = -0.0980383578888048;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 2))  {
        _temp_6 = -0.190483001883647;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 3))  {
        _temp_6 = -0.0782172290689705;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 4))  {
        _temp_6 = 0.389905680236479;
    }
    if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 0))  {
        _temp_7 = 0.0136071263944563;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 1))  {
        _temp_7 = 0.335078989210173;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 2))  {
        _temp_7 = 0.149633813130539;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 3))  {
        _temp_7 = 0.150296158398885;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 4))  {
        _temp_7 = -0.648616087134054;
    }
    if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 0))  {
        _temp_8 = -0.0599133088158337;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 1))  {
        _temp_8 = -0.125417548212461;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 2))  {
        _temp_8 = 0.0588605257066206;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 3))  {
        _temp_8 = 0.0351736522971962;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 4))  {
        _temp_8 = 0.0428760299583553;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 5))  {
        _temp_8 = -0.0599235427507984;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 6))  {
        _temp_8 = 0.108344191816921;
    }
    if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 0))  {
        _temp_9 = -0.0116646056500132;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 1))  {
        _temp_9 = -0.493219300299112;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 2))  {
        _temp_9 = -0.00551720816878298;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 3))  {
        _temp_9 = 0.0103492349547416;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 4))  {
        _temp_9 = 0.133717235842844;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 5))  {
        _temp_9 = -0.0523435097767914;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 6))  {
        _temp_9 = -0.0072796713240541;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 7))  {
        _temp_9 = 0.425957824421168;
    }
    H1_6_1 = 0.0359463840939424 + -0.00550251935634714 * Math.log(((-11.6322367884617 + indata["Age.at.Initial.Diagnosis"]) / (89.6435132764535 + -1 * indata["Age.at.Initial.Diagnosis"]))) + _temp_0 + _temp_1 + _temp_2 + _temp_3 + _temp_4 + _temp_5 + _temp_6 + _temp_7 + _temp_8 + _temp_9;

    if (jmp.numeq(Sex_M_1_F_2__asCode, 0))  {
        _temp_0 = -0.0577612124893146;
    }
    else if (jmp.numeq(Sex_M_1_F_2__asCode, 1))  {
        _temp_0 = 0.0577612124893146;
    }
    if (jmp.numeq(WHO_Grade_2_2_asCode, 0))  {
        _temp_1 = 0.124025251540226;
    }
    else if (jmp.numeq(WHO_Grade_2_2_asCode, 1))  {
        _temp_1 = -0.124025251540226;
    }
    if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 0))  {
        _temp_2 = -1.11953749043032;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 1))  {
        _temp_2 = 0.644313107458787;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 2))  {
        _temp_2 = 0.475224382971533;
    }
    if (jmp.numeq(Seizure_preop_2_asCode, 0))  {
        _temp_3 = -0.0969480525910766;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 1))  {
        _temp_3 = 0.929072886525843;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 2))  {
        _temp_3 = -0.832124833934766;
    }
    if (jmp.numeq(TMZ_anytime_2_2_asCode, 0))  {
        _temp_4 = -0.182373702888492;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 1))  {
        _temp_4 = -0.644432558996272;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 2))  {
        _temp_4 = 0.826806261884764;
    }
    if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 0))  {
        _temp_5 = 1.10163793356178;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 1))  {
        _temp_5 = -1.22465604435245;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 2))  {
        _temp_5 = 0.313040425606193;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 3))  {
        _temp_5 = -0.19002231481552;
    }
    if (jmp.numeq(KPS_post_op_3_asCode, 0))  {
        _temp_6 = -0.898649691213452;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 1))  {
        _temp_6 = 0.305199991250185;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 2))  {
        _temp_6 = 0.254838623597391;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 3))  {
        _temp_6 = 0.109683794659393;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 4))  {
        _temp_6 = 0.228927281706484;
    }
    if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 0))  {
        _temp_7 = -0.0223826486612602;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 1))  {
        _temp_7 = -0.937914425346173;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 2))  {
        _temp_7 = -0.395702885172474;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 3))  {
        _temp_7 = 1.97003022209281;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 4))  {
        _temp_7 = -0.614030262912904;
    }
    if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 0))  {
        _temp_8 = -0.806583742159504;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 1))  {
        _temp_8 = 0.153672377754455;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 2))  {
        _temp_8 = -0.581948229579994;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 3))  {
        _temp_8 = -1.13142461753869;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 4))  {
        _temp_8 = -0.78203034272348;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 5))  {
        _temp_8 = -0.52311508141304;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 6))  {
        _temp_8 = 3.67142963566026;
    }
    if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 0))  {
        _temp_9 = -0.0538659281750894;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 1))  {
        _temp_9 = 1.3914340484576;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 2))  {
        _temp_9 = 0.37224598215242;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 3))  {
        _temp_9 = 1.24923835368553;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 4))  {
        _temp_9 = -0.419317506851004;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 5))  {
        _temp_9 = 0.769493129600119;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 6))  {
        _temp_9 = -0.579048829745181;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 7))  {
        _temp_9 = -2.73017924912439;
    }
    H1_7_1 = Math.exp(-((0.5 * Math.pow((-4.35958256076875 + -1.08919185949142 * Math.log(((-11.6322367884617 + indata["Age.at.Initial.Diagnosis"]) / (89.6435132764535 + -1 * indata["Age.at.Initial.Diagnosis"]))) + _temp_0 + _temp_1 + _temp_2 + _temp_3 + _temp_4 + _temp_5 + _temp_6 + _temp_7 + _temp_8 + _temp_9), 2))));

    if (jmp.numeq(Sex_M_1_F_2__asCode, 0))  {
        _temp_0 = 0.217882885183796;
    }
    else if (jmp.numeq(Sex_M_1_F_2__asCode, 1))  {
        _temp_0 = -0.217882885183796;
    }
    if (jmp.numeq(WHO_Grade_2_2_asCode, 0))  {
        _temp_1 = 0.496505922571002;
    }
    else if (jmp.numeq(WHO_Grade_2_2_asCode, 1))  {
        _temp_1 = -0.496505922571002;
    }
    if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 0))  {
        _temp_2 = 0.341784591270637;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 1))  {
        _temp_2 = -0.931325852463208;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 2))  {
        _temp_2 = 0.58954126119257;
    }
    if (jmp.numeq(Seizure_preop_2_asCode, 0))  {
        _temp_3 = -0.994323627839757;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 1))  {
        _temp_3 = 0.287073828552945;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 2))  {
        _temp_3 = 0.707249799286812;
    }
    if (jmp.numeq(TMZ_anytime_2_2_asCode, 0))  {
        _temp_4 = 0.648073338248713;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 1))  {
        _temp_4 = -0.690780666933947;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 2))  {
        _temp_4 = 0.0427073286852345;
    }
    if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 0))  {
        _temp_5 = -0.521781766115654;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 1))  {
        _temp_5 = 1.01739392919001;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 2))  {
        _temp_5 = 1.19441458986366;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 3))  {
        _temp_5 = -1.69002675293802;
    }
    if (jmp.numeq(KPS_post_op_3_asCode, 0))  {
        _temp_6 = 0.325386548345451;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 1))  {
        _temp_6 = -0.492302745360807;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 2))  {
        _temp_6 = 1.09403921678605;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 3))  {
        _temp_6 = 0.95590218141782;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 4))  {
        _temp_6 = -1.88302520118851;
    }
    if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 0))  {
        _temp_7 = 0.239115576752233;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 1))  {
        _temp_7 = -0.0468150684340122;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 2))  {
        _temp_7 = -0.757986674675279;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 3))  {
        _temp_7 = 0.267494498826884;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 4))  {
        _temp_7 = 0.298191667530174;
    }
    if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 0))  {
        _temp_8 = -0.331121401462551;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 1))  {
        _temp_8 = 0.782002028689001;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 2))  {
        _temp_8 = -0.361608744441311;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 3))  {
        _temp_8 = 0.580391776565885;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 4))  {
        _temp_8 = -0.552972229620504;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 5))  {
        _temp_8 = 0.466436789376135;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 6))  {
        _temp_8 = -0.583128219106656;
    }
    if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 0))  {
        _temp_9 = 1.69710817488746;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 1))  {
        _temp_9 = -0.105695627263515;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 2))  {
        _temp_9 = 0.267466367742961;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 3))  {
        _temp_9 = -0.633897059708026;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 4))  {
        _temp_9 = 0.365281126572863;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 5))  {
        _temp_9 = -0.00549910577408719;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 6))  {
        _temp_9 = -1.2914494278209;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 7))  {
        _temp_9 = -0.293314448636759;
    }
    H1_8_1 = Math.exp(-((0.5 * Math.pow((1.27765415756606 + 0.235787509260754 * Math.log(((-11.6322367884617 + indata["Age.at.Initial.Diagnosis"]) / (89.6435132764535 + -1 * indata["Age.at.Initial.Diagnosis"]))) + _temp_0 + _temp_1 + _temp_2 + _temp_3 + _temp_4 + _temp_5 + _temp_6 + _temp_7 + _temp_8 + _temp_9), 2))));

    if (jmp.numeq(Sex_M_1_F_2__asCode, 0))  {
        _temp_0 = -0.202600340996706;
    }
    else if (jmp.numeq(Sex_M_1_F_2__asCode, 1))  {
        _temp_0 = 0.202600340996706;
    }
    if (jmp.numeq(WHO_Grade_2_2_asCode, 0))  {
        _temp_1 = 0.197514266787353;
    }
    else if (jmp.numeq(WHO_Grade_2_2_asCode, 1))  {
        _temp_1 = -0.197514266787353;
    }
    if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 0))  {
        _temp_2 = 0.862016857989237;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 1))  {
        _temp_2 = -0.636283581205119;
    }
    else if (jmp.numeq(Ethnicity_Hispanic_Latino_Yes_1_No_2_2_asCode, 2))  {
        _temp_2 = -0.225733276784117;
    }
    if (jmp.numeq(Seizure_preop_2_asCode, 0))  {
        _temp_3 = -1.47339459072692;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 1))  {
        _temp_3 = 0.584635532910677;
    }
    else if (jmp.numeq(Seizure_preop_2_asCode, 2))  {
        _temp_3 = 0.888759057816238;
    }
    if (jmp.numeq(TMZ_anytime_2_2_asCode, 0))  {
        _temp_4 = 1.21582370005825;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 1))  {
        _temp_4 = 0.536672449618453;
    }
    else if (jmp.numeq(TMZ_anytime_2_2_asCode, 2))  {
        _temp_4 = -1.7524961496767;
    }
    if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 0))  {
        _temp_5 = 0.0537307481939827;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 1))  {
        _temp_5 = -0.920824895212684;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 2))  {
        _temp_5 = 0.0355208318456351;
    }
    else if (jmp.numeq(Employed_Y_1_N_2_Retired_3_2_asCode, 3))  {
        _temp_5 = 0.831573315173066;
    }
    if (jmp.numeq(KPS_post_op_3_asCode, 0))  {
        _temp_6 = 0.513660782968751;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 1))  {
        _temp_6 = 0.268121345282124;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 2))  {
        _temp_6 = -0.333896884568899;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 3))  {
        _temp_6 = -0.937488768429666;
    }
    else if (jmp.numeq(KPS_post_op_3_asCode, 4))  {
        _temp_6 = 0.48960352474769;
    }
    if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 0))  {
        _temp_7 = -1.45702574284085;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 1))  {
        _temp_7 = -0.666934055486511;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 2))  {
        _temp_7 = -0.123608646905161;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 3))  {
        _temp_7 = -2.1545261564502;
    }
    else if (jmp.numeq(Reordered_insurance_at_diagnosis_2_2_asCode, 4))  {
        _temp_7 = 4.40209460168272;
    }
    if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 0))  {
        _temp_8 = -0.449557985154255;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 1))  {
        _temp_8 = 0.0939738731122318;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 2))  {
        _temp_8 = 0.792417627821099;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 3))  {
        _temp_8 = 0.181962929933143;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 4))  {
        _temp_8 = -0.982482392772902;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 5))  {
        _temp_8 = 0.275860015623226;
    }
    else if (jmp.numeq(Updated_Race_White_Black_African_American_Hispanic_Latino_Asian_Pacific_Islander_American_Indian_Alaska_Native_3_2_asCode, 6))  {
        _temp_8 = 0.0878259314374564;
    }
    if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 0))  {
        _temp_9 = 1.07406634313245;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 1))  {
        _temp_9 = -1.34179121865488;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 2))  {
        _temp_9 = -1.21055497321714;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 3))  {
        _temp_9 = 0.636643338138123;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 4))  {
        _temp_9 = -1.66728327334391;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 5))  {
        _temp_9 = -0.179731170536448;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 6))  {
        _temp_9 = -0.0333527806278682;
    }
    else if (jmp.numeq(New_Tumor_Lobe_updated_chart_review_2_2_2_asCode, 7))  {
        _temp_9 = 2.72200373510968;
    }
    H1_9_1 = Math.exp(-((0.5 * Math.pow((2.22097804329652 + -0.690691704984999 * Math.log(((-11.6322367884617 + indata["Age.at.Initial.Diagnosis"]) / (89.6435132764535 + -1 * indata["Age.at.Initial.Diagnosis"]))) + _temp_0 + _temp_1 + _temp_2 + _temp_3 + _temp_4 + _temp_5 + _temp_6 + _temp_7 + _temp_8 + _temp_9), 2))));

    outdata["ProbabilityEnroll"] = Math.exp((-0.273226016563499 + -1.80645679442798 * H1_1_1 + -0.77895470608501 * H1_2_1 + -1.89821124716197 * H1_3_1 + 0.314967504762217 * H1_4_1 + 0.561220256058679 * H1_5_1 + 0.530126799500377 * H1_6_1 + 1.18319822352536 * H1_7_1 + -1.66722221579816 * H1_8_1 + -1.82863696757109 * H1_9_1)) / (1 + Math.exp((-0.273226016563499 + -1.80645679442798 * H1_1_1 + -0.77895470608501 * H1_2_1 + -1.89821124716197 * H1_3_1 + 0.314967504762217 * H1_4_1 + 0.561220256058679 * H1_5_1 + 0.530126799500377 * H1_6_1 + 1.18319822352536 * H1_7_1 + -1.66722221579816 * H1_8_1 + -1.82863696757109 * H1_9_1)));

    outdata["ProbabilityNotEnroll"] = 1 / (1 + Math.exp((-0.273226016563499 + -1.80645679442798 * H1_1_1 + -0.77895470608501 * H1_2_1 + -1.89821124716197 * H1_3_1 + 0.314967504762217 * H1_4_1 + 0.561220256058679 * H1_5_1 + 0.530126799500377 * H1_6_1 + 1.18319822352536 * H1_7_1 + -1.66722221579816 * H1_8_1 + -1.82863696757109 * H1_9_1)));

    _temp_11[0] = outdata["ProbabilityEnroll"];
    _temp_11[1] = outdata["ProbabilityNotEnroll"];
    _temp_10 = jmp.max_array(2, _temp_11);
    switch (_temp_10) {
        case 0: {
            _temp_0 = 1;
        }
        break;
        case 1: {
            _temp_0 = 2;
        }
        break;
        default: {
            _temp_0 = undefined;
        }
    }
    outdata["MostLikelyClinicalTrial"] = _temp_0;

    return outdata["MostLikelyClinicalTrial"];
};
console.log(typeof score);
